name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
      actions: read # Required for Claude to read CI results on PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Set up GitHub Actions caching for Wireit
        uses: google/wireit@setup-github-actions-caching/v2

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@v1
        env:
          NODE_VERSION: '22.x'
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # This is an optional setting that allows Claude to read CI results on PRs
          additional_permissions: |
            actions: read

          # Configure Claude CLI arguments
          claude_args: |
            --allowedTools "Bash(pnpm install),
            Bash(pnpm run *),
            Bash(pnpm dev:*),
            Bash(pnpm typecheck),
            Bash(pnpm build),
            Bash(pnpm test:*),
            Bash(bun run *),
            Bash(pnpm wrangler *),
            Bash(git status),
            Bash(git diff),
            Bash(git log),
            Bash(git add),
            Bash(git commit),
            Bash(tmux list-sessions),
            Edit,
            Read,
            Write,
            Glob,
            Grep,
            List,
            WebFetch,
            TodoWrite,
            TodoRead,
            Task"

          # Optional: Specify model (defaults to Claude Sonnet 4, uncomment for Claude Opus 4.1)
          # claude_args: |
          #   --model claude-opus-4-1-20250805

          # Optional: Customize the trigger phrase (default: @claude)
          # trigger_phrase: "/claude"

          # Optional: Trigger when specific user is assigned to an issue
          # assignee_trigger: "claude-bot"

          # Optional: Custom environment variables for Claude
          # settings: |
          #   {
          #     "env": {
          #       "NODE_ENV": "test"
          #     }
          #   }
